version: "3.9"
services:
  db:
    image: postgres:alpine
    environment:
      - POSTGRES_HOST_AUTH_METHOD=md5
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=app
    ports:
      - "5432:5432"
    volumes:
      - ~/docker/db:/var/lib/postgresql/data
      - ./scripts/postgres.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql
  api:
    image: tezos-delegation-service
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      - GIN_MODE=release
      - STORAGE_HOST=database
    links:
      - "db:database"
